registry: us-central1-docker.pkg.dev/project-54ecee29-e768-42f3-977/devops-repo

ecomifyCustomers:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/project-54ecee29-e768-42f3-977/devops-repo/ecomify-customers
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 8080
  containerPort: 8080

backend:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/project-54ecee29-e768-42f3-977/devops-repo/backend
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 8080
  containerPort: 8080
  env: []

productos:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/project-54ecee29-e768-42f3-977/devops-repo/productos
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 5000
  containerPort: 5000
  env:
    - name: ConnectionStrings__DefaultConnection
      value: "Data Source=/tmp/productos.db"

frontend:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/project-54ecee29-e768-42f3-977/devops-repo/frontend
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
  containerPort: 80
  backendUrl: "http://backend:8080"
  productosUrl: "http://productos:5000"
