apiVersion: v1
kind: Service
metadata:
  name: ecomify-customers
  labels:
    app: ecomify-customers
spec:
  type: {{ .Values.ecomifyCustomers.service.type }}
  selector:
    app: ecomify-customers
  ports:
    - protocol: TCP
      port: {{ .Values.ecomifyCustomers.service.port }}
      targetPort: {{ .Values.ecomifyCustomers.containerPort }}
